[package]
name = "slint_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.12.1"
tokio = { version = "1.46.1", features = ["full"] }

[build-dependencies]
slint-build = "1.12.1"
