import { Button, VerticalBox } from "std-widgets.slint";
import { Pages } from "page/adapta.slint";
export component AnimatedButton inherits Rectangle {
    in property <string> label: "버튼";
    property <bool> hovered: false;
    property <bool> pressed: false;
    
    in property <int> index: 0;
    in property <int> selected_menu: 0;
    callback clicked_with_index(int);

    // 기본 사이즈/스타일
    

    width: 100px;
    height: 30px;
    // background: area.pressed ? #fff: #737cc9;
    background: root.selected_menu ==0 ? #000008 
    : root.selected_menu ==1 ?#0e0c91
    : root.selected_menu ==2 ?#ff0325
    :#fff;
    // background: pressed ? #792fcf : #9f4ccf;
    border-radius: 8px;
    padding: area.pressed ? 20px : 0px;    // 눌리면 안쪽으로 줄어드는 효과!
    animate padding { duration: 80ms; }
    animate background { duration: 120ms; }

    area := TouchArea {
        x: 0; y: 0;
        width: parent.width;
        height: parent.height;
        clicked => { root.clicked_with_index(root.index); }

        // clicked => { /* ... */ }
    }

    // 텍스트와 밑줄
    VerticalLayout {
        spacing: 0px;
        padding: 2px;
        
        Text {
            text: root.label;
            font-weight: root.index == root.selected_menu ? 900 : 400;
            // color: root.index == root.selected_menu ? #0e0c91 : #fff;
            color: root.selected_menu ==0 &&root.index==0 ? #000008 
            : root.selected_menu ==1 &&root.index==1?#0e0c91
            : root.selected_menu ==2 &&root.index==2?#ff0325
            :#fff;
            // color: hovered ? #ffffff : #ddddff;
            font-size: root.index == root.selected_menu ? 20px : 16px;
            // font-size: 16px;
            animate font-size { duration: 200ms; }
            // animate color { duration: 100ms; }
            animate color { duration: 200ms; }
            horizontal-alignment: center;
        }
        
        Rectangle {
            height: 2px;
            width: parent.width;
            

            // background: #fff;
            opacity: hovered ? 1.0 : 0.0;
            animate opacity { duration: 200ms; }
        }
    }

    // (더 다양한 효과 가능: 그림자, border-color 등)
}

export component AppWindow inherits Window {
    in-out property <int> selected_menu: 0;
    in-out property <string> status_text: "시작!";
    preferred-width: 800px;
    preferred-height: 900px;
    in-out property <int> counter: 42;
    callback request-increase-value();
    callback clicked_with_index(int);
    VerticalLayout {
        
        Rectangle {   
               // 메뉴바
            // height: 32px;
            // width: self.preferred-width;
            height: 35px;
            border-radius: 9px;
            background: #8c8c8f;
            
            
            
            HorizontalLayout {
                // spacing: 10px;
                padding: 2px;
                AnimatedButton { 
                    label: "MAIN"; 
                    index: 0;
                    selected_menu: root.selected_menu;

                    clicked_with_index(i) => { root.selected_menu = i; }
                    background: root.selected_menu == 0 ? #fff 
                    : root.selected_menu ==1 ?#737cc9
                    : root.selected_menu ==2 ?#ff0325
                    :#fff;
                    
                    // background: root.selected_menu == 0 ? #FFD700 : #8c4ccf;

                }
                Rectangle { 
                    width:
                    root.selected_menu == 0 ? 15px
                    :root.selected_menu == 1 ? 15px
                    :4px;
                    animate width { duration: 180ms; }
                } 
                AnimatedButton { 
                    label: "Serial"; 
                    index: 1;
                    selected_menu: root.selected_menu;

                    clicked_with_index(i) => { root.selected_menu = i; }
                    // background: area.pressed ? #fff: #737cc9;
                    background: root.selected_menu == 0 ? #000008 
                    : root.selected_menu ==1 ?#ffffff
                    : root.selected_menu ==2 ?#ff0325
                    :#fff;
                    // background: root.selected_menu == 1 ? #fff : #737cc9;

                }
                Rectangle { 
                    width:
                    root.selected_menu == 0 ? 4px
                    :root.selected_menu == 1 ? 15px
                    :root.selected_menu == 2 ? 15px
                    :4px;
                    animate width { duration: 180ms; }
                } 
                
                AnimatedButton { 
                    label: "Temp"; 
                    index: 2;
                    selected_menu: root.selected_menu;

                    clicked_with_index(i) => { root.selected_menu = i; }
                    background: root.selected_menu == 0 ? #000008 
                    : root.selected_menu ==1 ?#737cc9
                    : root.selected_menu ==2 ?#ffffff
                    :#fff;
                    // background: root.selected_menu == 2 ? #fff : #737cc9;
                    // background: root.selected_menu == 2 ? #FFD700 : #8c4ccf;

                }
                // Rectangle { min-width: 0px; }  
                // Text { text: "파일"; color: #fff; font-size: 16px; }
                // Text { text: "편집"; color: #fff; font-size: 16px; }
                // Text { text: "도움말"; color: #fff; font-size: 16px; }
                Rectangle { min-width: 0px; } 
                // Image {
                //     width: 85px;  
                //     height: 35px;
                //     image-fit: contain;
                //     source: @image-url("images/eomi_stm_logo.png");
                // } 
            }
            
        }
        Pages {
            selected_menu: root.selected_menu;
            status_text: root.status_text;
        }
        // if(root.selected_menu == 0) : Main {}
        // if(root.selected_menu == 1) : Serial {}
        // if(root.selected_menu == 2) : Temp {}
        // Rectangle {      // 여기서부터 “내용” 영역
        //     background: #ebe3e3;
        //     border-radius: 12px;
            
        // }
    }
}


